CREATE TABLE `cta_strategy` (
	`id` int UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'ID',
	`strategy` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT '' COMMENT '策略账户名称',
	`trade_type` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT '' COMMENT '策略类型,spot,margin,future,delivery',
	`is_pm` tinyint UNSIGNED NOT NULL DEFAULT 1 COMMENT '是否统一账户',
	`is_running` tinyint UNSIGNED NOT NULL DEFAULT 0 COMMENT '是否运行',
	`symbol` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT '' COMMENT '交易对',
	`interval` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT '' COMMENT '时间间隔',
	`cta` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT '' COMMENT 'cta策略名',
	`period` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT '' COMMENT 'cta参数',
	`signal` int NOT NULL DEFAULT 0 COMMENT '当前信号',
	`signal_time` datetime NULL COMMENT '当前信号产生时间',
	`open_price` decimal(20,6)  NULL COMMENT '策略开仓价',
	`close_price` decimal(20,6)  NULL COMMENT '策略上次平仓价格',
	`position_amount` decimal(20,5)  NOT NULL DEFAULT 0.00000 COMMENT '当前仓位',
	`init_value` decimal(10,2)  NOT NULL DEFAULT 0.00 COMMENT '策略初始开仓金额',
	`profit` decimal(10,2)  NOT NULL DEFAULT 0.00 COMMENT '策略盈利',
	`net_value` decimal(10,2)  UNSIGNED NOT NULL DEFAULT 1.00 COMMENT '策略当前净值',
	`trade_ratio` decimal(10,2)  UNSIGNED NOT NULL DEFAULT 1.00 COMMENT '策略杠杆',
	`takeprofit_percentage` decimal(10,2)  UNSIGNED NOT NULL DEFAULT 0.30 COMMENT '止盈比例',
	`takeprofit_drawdown_percentage` decimal(10,2)  UNSIGNED NOT NULL DEFAULT 0.10 COMMENT '吊灯止盈回调比例',
	`stoploss_percentage` decimal(10,2)  UNSIGNED NOT NULL DEFAULT 0.10 COMMENT '止损比例',
	`open_tpsl` tinyint UNSIGNED NOT NULL DEFAULT 1 COMMENT '是否开启止盈止损',
	`is_tpsl` tinyint UNSIGNED NOT NULL DEFAULT 0 COMMENT '是否已触发止盈止损',
	`is_del` tinyint UNSIGNED NOT NULL DEFAULT 0 COMMENT '是否软删除',
	`update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '上次更新时间',
	PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARACTER SET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
;